version: '3.1'

services:
  db:
    image: mysql:8
    # container_name: mysql-gym
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: nestjs_gym_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-gym
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db # phải đúng tên service MySQL
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - db # phpMyAdmin sẽ chờ db start trước

volumes:
  mysql-data:
